---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: chitranshkul07
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "chitranshkul07/react_calculators"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    
    - name: Remove existing container if running
      shell: docker rm -f react_calculators
      ignore_errors: true

    - name: Running container
      shell: docker run -it -d --name react_calculators chitranshkul07/react_calculators
